package com.atguigu.finance.dao;

import com.atguigu.finance.bean.NplmRepaymentPlan;
import com.atguigu.finance.bean.NplmRepaymentPlanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NplmRepaymentPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int countByExample(NplmRepaymentPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByExample(NplmRepaymentPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insert(NplmRepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insertSelective(NplmRepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    List<NplmRepaymentPlan> selectByExample(NplmRepaymentPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    NplmRepaymentPlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") NplmRepaymentPlan record, @Param("example") NplmRepaymentPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByExample(@Param("record") NplmRepaymentPlan record, @Param("example") NplmRepaymentPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(NplmRepaymentPlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_plan
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKey(NplmRepaymentPlan record);

    List<NplmRepaymentPlan> getByContractNum(String loanContractNum);
}