package com.atguigu.finance.dao;

import com.atguigu.finance.bean.NplmRepaymentDetail;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NplmRepaymentDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insert(NplmRepaymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insertSelective(NplmRepaymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    NplmRepaymentDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(NplmRepaymentDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_detail
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKey(NplmRepaymentDetail record);

    List<NplmRepaymentDetail> getDetailByContractNum(String loanContractNum);
}