package com.atguigu.finance.dao;

import com.atguigu.finance.bean.NplmLoanContract;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NplmLoanContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insert(NplmLoanContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insertSelective(NplmLoanContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    NplmLoanContract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(NplmLoanContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_loan_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKey(NplmLoanContract record);
}