package com.atguigu.finance.dao;

import com.atguigu.finance.bean.NplmOverdueContract;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NplmOverdueContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insert(NplmOverdueContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insertSelective(NplmOverdueContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    NplmOverdueContract selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(NplmOverdueContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_overdue_contract
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKey(NplmOverdueContract record);
}