package com.atguigu.finance.dao;

import com.atguigu.finance.bean.NplmBorrowerInfo;
import com.atguigu.finance.bean.NplmBorrowerInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NplmBorrowerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int countByExample(NplmBorrowerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByExample(NplmBorrowerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insert(NplmBorrowerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int insertSelective(NplmBorrowerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    List<NplmBorrowerInfo> selectByExample(NplmBorrowerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    NplmBorrowerInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") NplmBorrowerInfo record, @Param("example") NplmBorrowerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByExample(@Param("record") NplmBorrowerInfo record, @Param("example") NplmBorrowerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(NplmBorrowerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_borrower_info
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKey(NplmBorrowerInfo record);
}