package com.atguigu.finance.dao;

import com.atguigu.finance.bean.NplmRepaymentRecord;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NplmRepaymentRecordMapper {


    List<NplmRepaymentRecord> getByRecordContractNum(String loanContractNum);



    NplmRepaymentRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_record
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_record
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_record
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(NplmRepaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nplm_repayment_record
     *
     * @mbggenerated Mon Sep 17 11:44:58 CST 2018
     */
    int updateByPrimaryKey(NplmRepaymentRecord record);
}